import '../services/notification_service.dart';
import '../models/notification_model.dart';

/// Helper class for sending notifications (for testing/admin purposes)
class NotificationHelper {
  static final NotificationService _notificationService = NotificationService();

  /// Send a test order notification
  static Future<void> sendOrderNotification(
    String userId,
    String orderId,
    String orderStatus,
  ) async {
    final notification = NotificationModel(
      id: '', // Will be auto-generated by Firestore
      userId: userId,
      title: 'Order Update',
      body: 'Your order #$orderId is now $orderStatus',
      type: NotificationType.order,
      data: {'orderId': orderId, 'status': orderStatus},
      createdAt: DateTime.now(),
    );

    await _notificationService.sendNotification(notification);
  }

  /// Send a test promotion notification
  static Future<void> sendPromotionNotification(
    String userId,
    String title,
    String message,
  ) async {
    final notification = NotificationModel(
      id: '',
      userId: userId,
      title: title,
      body: message,
      type: NotificationType.promotion,
      createdAt: DateTime.now(),
    );

    await _notificationService.sendNotification(notification);
  }

  /// Send a test product notification
  static Future<void> sendProductNotification(
    String userId,
    String productId,
    String productName,
  ) async {
    final notification = NotificationModel(
      id: '',
      userId: userId,
      title: 'New Product Available',
      body: 'Check out $productName now available in store!',
      type: NotificationType.product,
      data: {'productId': productId},
      createdAt: DateTime.now(),
    );

    await _notificationService.sendNotification(notification);
  }

  /// Send a test system notification
  static Future<void> sendSystemNotification(
    String userId,
    String title,
    String message,
  ) async {
    final notification = NotificationModel(
      id: '',
      userId: userId,
      title: title,
      body: message,
      type: NotificationType.system,
      createdAt: DateTime.now(),
    );

    await _notificationService.sendNotification(notification);
  }

  /// Send welcome notification to new users
  static Future<void> sendWelcomeNotification(String userId) async {
    await sendSystemNotification(
      userId,
      'Welcome to TryVerse! 🎉',
      'Thank you for joining us. Start exploring amazing products with AR try-on feature!',
    );
  }

  /// Send notification when order is placed
  static Future<void> sendOrderPlacedNotification(
    String userId,
    String orderId,
    double totalAmount,
  ) async {
    final notification = NotificationModel(
      id: '',
      userId: userId,
      title: 'Order Placed Successfully! 🛍️',
      body: 'Your order #$orderId for Rs. ${totalAmount.toStringAsFixed(2)} has been placed successfully.',
      type: NotificationType.order,
      data: {'orderId': orderId, 'status': 'placed'},
      createdAt: DateTime.now(),
    );

    await _notificationService.sendNotification(notification);
  }

  /// Send notification when order is shipped
  static Future<void> sendOrderShippedNotification(
    String userId,
    String orderId,
    String trackingNumber,
  ) async {
    final notification = NotificationModel(
      id: '',
      userId: userId,
      title: 'Order Shipped! 📦',
      body: 'Your order #$orderId has been shipped. Tracking: $trackingNumber',
      type: NotificationType.order,
      data: {'orderId': orderId, 'status': 'shipped', 'tracking': trackingNumber},
      createdAt: DateTime.now(),
    );

    await _notificationService.sendNotification(notification);
  }

  /// Send notification when order is delivered
  static Future<void> sendOrderDeliveredNotification(
    String userId,
    String orderId,
  ) async {
    final notification = NotificationModel(
      id: '',
      userId: userId,
      title: 'Order Delivered! ✅',
      body: 'Your order #$orderId has been delivered. Hope you enjoy your purchase!',
      type: NotificationType.order,
      data: {'orderId': orderId, 'status': 'delivered'},
      createdAt: DateTime.now(),
    );

    await _notificationService.sendNotification(notification);
  }
}
